let state = null;
let view = 'home';
let toast = '';
let ruleIntroOpen = false;
let logOpen = false;
let roomRef = null;
let aiTimer = null;
const app = document.getElementById('app');
const $ = (id) => document.getElementById(id);
const SESSION_KEY = 'zjhCurrentPlayerSession';
const savedSession = restoreLocalSession();
let playerId = savedSession?.playerId || `P_${Math.random().toString(36).slice(2, 10)}_${Date.now().toString(36)}`;
const SUITS = ['♠', '♥', '♣', '♦'];
const RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
const VAL = Object.fromEntries(RANKS.map((r, i) => [r, i + 2]));
const DEFAULT_SETTINGS = { maxPlayers: 4, initialPoints: 1000, ante: 50, allowAI: true, aiDifficulty: 'normal' };
const firebaseConfigForApp = window.firebaseConfig || null;
const firebaseConfigText = JSON.stringify(firebaseConfigForApp || {});
const hasFirebaseConfig = !!(firebaseConfigForApp && firebaseConfigForApp.apiKey && firebaseConfigForApp.databaseURL && !firebaseConfigText.includes('YOUR_') && !firebaseConfigText.includes('REPLACE_WITH'));
let db = null;
if (hasFirebaseConfig && window.firebase) {
  firebase.initializeApp(firebaseConfigForApp);
  db = firebase.database();
}
function showToast(message) { toast = message; render(); }
function go(nextView) { view = nextView; render(); }
function nickname(id) { return $(id)?.value.trim() || `玩家${Math.floor(1000 + Math.random() * 9000)}`; }
function defaultLocalSettings() { return { ...DEFAULT_SETTINGS }; }
function settings(prefix = '') { const g = (n) => $(`${prefix}${n}`); return { maxPlayers: clamp(+g('maxPlayers')?.value || 4, 2, 8), initialPoints: clamp(+g('initialPoints')?.value || 1000, 100, 99999), ante: clamp(+g('ante')?.value || 50, 1, 9999), allowAI: g('allowAI')?.checked ?? true, aiDifficulty: g('aiDifficulty')?.value || 'normal' }; }
function clamp(n, min, max) { return Math.max(min, Math.min(max, Number.isFinite(n) ? n : min)); }
function saveLocalSession(roomCode, id = playerId, nick = '') { try { const data = { roomCode, playerId: id, nickname: nick, savedAt: Date.now() }; sessionStorage.setItem(SESSION_KEY, JSON.stringify(data)); localStorage.setItem(SESSION_KEY, JSON.stringify(data)); } catch (_) {} }
function restoreLocalSession() { try { return JSON.parse(sessionStorage.getItem(SESSION_KEY) || localStorage.getItem(SESSION_KEY) || 'null'); } catch (_) { return null; } }
function resumeSavedOnlineRoom() { const session = restoreLocalSession(); if (session?.roomCode && session?.playerId && db) { playerId = session.playerId; view = 'roomLobby'; listenRoom(session.roomCode); } }
function getMyPlayer() { const session = restoreLocalSession(); const ids = [playerId, session?.playerId].filter(Boolean); const found = state?.players?.find((p) => ids.includes(p.id)); if (found) { playerId = found.id; return found; } return null; }
function generateRoomCode() { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; let code = ''; for (let i = 0; i < 10; i++) code += chars[Math.floor(Math.random() * chars.length)]; return code; }
function addLog(room, message) { room.logs = [`[${new Date().toLocaleTimeString()}] ${message}`, ...(room.logs || [])].slice(0, 80); }
function makePlayer({ id, nickname, isHost = false, isAI = false, aiDifficulty = 'normal' }) { return { id, nickname, isHost, isAI, aiDifficulty, online: true, ready: false, points: 0, bet: 0, looked: false, folded: false, eliminated: false, spectator: false, spectateTargetId: null, cards: [], hand: null, lastAction: '' }; }
function createRoomObject({ mode, nickname, settings }) { const roomCode = generateRoomCode(); const room = { roomCode, code: roomCode, mode, phase: 'waiting', settings: { ...DEFAULT_SETTINGS, ...settings }, players: [makePlayer({ id: playerId, nickname, isHost: true })], deck: [], pot: 0, currentBet: 0, round: 0, handNo: 0, currentPlayerId: null, logs: [], reveal: [], handResult: null, gameResult: null, createdAt: Date.now(), updatedAt: Date.now() }; addLog(room, `${nickname} 创建${mode === 'local' ? '单机' : '联机'}房间。`); return room; }
function writeRoom(next) { if (!next) return; next.updatedAt = Date.now(); state = structuredClone(next); if (state.mode === 'online' && roomRef) roomRef.set(next); render(); }
function listenRoom(code) { if (!db) return; if (roomRef) roomRef.off(); roomRef = db.ref(`rooms/${code}`); roomRef.on('value', (snap) => { const next = snap.val(); if (!next) { showToast('房间不存在或已删除。'); state = null; view = 'onlineEntry'; return; } state = next; view = next.phase === 'waiting' ? 'roomLobby' : 'gameTable'; render(); maybeRunAI(); }); }
function quickStartLocalGame() { const nick = nickname('soloNick'); const room = createRoomObject({ mode: 'local', nickname: nick, settings: defaultLocalSettings() }); saveLocalSession(room.code, playerId, nick); view = 'gameTable'; state = room; startGame(true); }
function startCustomLocalGame() { const nick = nickname('soloNick'); const room = createRoomObject({ mode: 'local', nickname: nick, settings: { ...settings('solo'), allowAI: true } }); saveLocalSession(room.code, playerId, nick); view = 'gameTable'; state = room; startGame(true); }
function createOnlineRoom() { if (!db) return showToast('请确认根目录 firebase-config.js 已填写真实 Firebase 配置，并使用 window.firebaseConfig = {...}。'); const nick = nickname('hostNick') || '房主'; const room = createRoomObject({ mode: 'online', nickname: nick, settings: settings('online') }); saveLocalSession(room.code, playerId, nick); view = 'roomLobby'; db.ref(`rooms/${room.code}`).set(room).then(() => listenRoom(room.code)); }
function joinRoom() { if (!db) return showToast('当前未配置 Firebase，无法使用联机模式。'); const code = ($('roomCode')?.value || '').trim().toUpperCase(); const nick = nickname('joinNick'); if (!code) return showToast('请输入房间码。'); db.ref(`rooms/${code}`).get().then((snap) => { const room = snap.val(); if (!room) return showToast('房间不存在。'); if (room.phase !== 'waiting') return showToast('游戏已开始，暂不能加入。'); if ((room.players || []).length >= room.settings.maxPlayers) return showToast('房间已满。'); room.players.push(makePlayer({ id: playerId, nickname: nick })); addLog(room, `${nick} 加入房间。`); saveLocalSession(code, playerId, nick); db.ref(`rooms/${code}`).set(room).then(() => listenRoom(code)); }); }
function copyRoomCode() { if (!state?.code) return showToast('暂无房间码'); navigator.clipboard?.writeText(state.code).then(() => showToast('房间码已复制')).catch(() => showToast('复制失败，请手动复制')); }
function me() { return getMyPlayer(); }
function isHost() { return !!me()?.isHost; }
function canAct() { const p = getMyPlayer(); return !!(state?.phase === 'playing' && p && state.currentPlayerId === p.id && !p.folded && !p.eliminated && !p.spectator); }
function activePlayers(room = state) { return (room.players || []).filter((p) => !p.eliminated && !p.spectator); }
function liveHandPlayers(room = state) { return activePlayers(room).filter((p) => !p.folded); }
function resetHandPlayer(p) { Object.assign(p, { bet: 0, looked: false, folded: false, cards: [], hand: null, lastAction: '' }); }
function fillAI(room) { if (!room.settings.allowAI) return; let n = room.players.filter((p) => p.isAI).length + 1; while (room.players.length < room.settings.maxPlayers) room.players.push(makePlayer({ id: `AI_${room.code}_${n}_${Date.now()}`, nickname: `AI ${n++}`, isAI: true, aiDifficulty: room.settings.aiDifficulty })); }
function startGame(forceAI = false) { const room = structuredClone(state); if (!room || room.phase === 'playing' || room.phase === 'dealing') return; if (forceAI) room.settings.allowAI = true; fillAI(room); if (room.players.length < 2) { addLog(room, '至少需要 2 名玩家才能开始。'); return writeRoom(room); } room.players.forEach((p) => { p.points = room.settings.initialPoints; p.eliminated = false; p.spectator = false; p.spectateTargetId = null; p.ready = false; resetHandPlayer(p); }); room.gameResult = null; addLog(room, '游戏开始，所有临时积分已发放。'); state = room; startHand(); }
function startHand() { const room = structuredClone(state); if (checkGameOver(room, false)) return; room.phase = 'dealing'; room.handNo += 1; room.round = 1; room.pot = 0; room.currentBet = room.settings.ante; room.reveal = []; room.handResult = null; room.deck = shuffleDeck(createDeck()); activePlayers(room).forEach((p) => { resetHandPlayer(p); p.cards = [room.deck.pop(), room.deck.pop(), room.deck.pop()]; p.hand = evaluateHand(p.cards); const ante = Math.min(p.points, room.settings.ante); p.points -= ante; p.bet = ante; room.pot += ante; }); room.currentPlayerId = liveHandPlayers(room)[0]?.id || null; addLog(room, `第 ${room.handNo} 手开始，正在发牌。`); writeRoom(room); setTimeout(() => { const next = structuredClone(state); if (next?.phase !== 'dealing') return; next.phase = 'playing'; addLog(next, '发牌完成，进入操作阶段。'); writeRoom(next); maybeRunAI(); }, 900); }
function createDeck() { const deck = []; for (const suit of SUITS) for (const rank of RANKS) deck.push({ rank, suit, value: VAL[rank], color: suit === '♥' || suit === '♦' ? 'red' : 'black' }); return deck; }
function shuffleDeck(deck) { for (let i = deck.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [deck[i], deck[j]] = [deck[j], deck[i]]; } return deck; }
function normalizeStraight(vals) { const s = [...vals].sort((a, b) => b - a); const key = s.join(','); if (key === '14,3,2') return [3, 2, 1]; if (key === '14,13,12') return [14, 13, 12]; if (s[0] - 1 === s[1] && s[1] - 1 === s[2]) return s; return null; }
function evaluateHand(cards) { const vals = cards.map((c) => c.value).sort((a, b) => b - a); const counts = {}; vals.forEach((v) => counts[v] = (counts[v] || 0) + 1); const flush = cards.every((c) => c.suit === cards[0].suit); const straight = normalizeStraight(vals); const entries = Object.entries(counts).map(([v, c]) => ({ v: +v, c })).sort((a, b) => b.c - a.c || b.v - a.v); let rank = 1, name = '散牌', values = vals; if (entries[0].c === 3) { rank = 6; name = '豹子'; values = [entries[0].v]; } else if (flush && straight) { rank = 5; name = '顺金'; values = straight; } else if (flush) { rank = 4; name = '金花'; } else if (straight) { rank = 3; name = '顺子'; values = straight; } else if (entries[0].c === 2) { rank = 2; name = '对子'; values = [entries[0].v, ...entries.filter((e) => e.c === 1).map((e) => e.v).sort((a, b) => b - a)]; } return { rank, name, values, description: `${cards.map((c) => c.rank + c.suit).join('、')} ${name}` }; }
function compareHands(a, b) { if (a.rank !== b.rank) return a.rank > b.rank ? 1 : -1; for (let i = 0; i < Math.max(a.values.length, b.values.length); i++) { const av = a.values[i] || 0, bv = b.values[i] || 0; if (av !== bv) return av > bv ? 1 : -1; } return 0; }
function validateTurn(room, p) { return room && p && room.phase === 'playing' && room.currentPlayerId === p.id && !p.eliminated && !p.spectator && !p.folded; }
function pay(room, p, amount) { const paid = Math.max(0, Math.min(p.points, amount)); p.points -= paid; p.bet += paid; room.pot += paid; return paid; }
function sendAction(action, aiPlayerId = null, extra = {}) { const room = structuredClone(state); const pid = aiPlayerId || playerId; const p = room.players.find((x) => x.id === pid); if (!validateTurn(room, p)) return; if (action === 'look') { p.looked = true; p.lastAction = '看牌'; addLog(room, `${p.nickname} 看牌。`); return writeRoom(room); } if (action === 'fold') { p.folded = true; p.lastAction = '弃牌'; addLog(room, `${p.nickname} 弃牌。`); return nextTurn(room); } if (action === 'call') { const need = Math.max(0, room.currentBet - p.bet); const paid = pay(room, p, need); addLog(room, `${p.nickname} ${paid < need ? '积分不足全下' : '跟注'} ${paid} 分。`); return nextTurn(room); } if (action === 'raise') { const amount = +(extra.amount ?? $('raiseAmount')?.value ?? room.currentBet + room.settings.ante); const target = Math.max(room.currentBet + 1, amount); const need = target - p.bet; const paid = pay(room, p, need); room.currentBet = Math.max(room.currentBet, p.bet); addLog(room, `${p.nickname} 加注到 ${room.currentBet} 分${paid < need ? '（全下）' : ''}。`); return nextTurn(room); } if (action === 'compare') { const targetId = extra.targetPlayerId || $('compareTarget')?.value; const t = liveHandPlayers(room).find((x) => x.id === targetId && x.id !== p.id); if (!t) return; const loser = compareHands(p.hand, t.hand) >= 0 ? t : p; loser.folded = true; loser.lastAction = '比牌失败'; addLog(room, `${p.nickname} 与 ${t.nickname} 比牌，${loser.nickname} 输掉本手。`); return nextTurn(room); } }
function nextTurn(room) { const live = liveHandPlayers(room); if (live.length <= 1) return finishHand(room, '只剩一名未弃牌玩家'); const idx = live.findIndex((p) => p.id === room.currentPlayerId); room.currentPlayerId = live[(idx + 1) % live.length].id; writeRoom(room); maybeRunAI(); }
function finishHand(room, reason) { room.phase = 'handFinished'; room.currentPlayerId = null; const contenders = liveHandPlayers(room); let winners = []; if (contenders.length === 1) winners = [contenders[0]]; else contenders.forEach((p) => { if (!winners.length || compareHands(p.hand, winners[0].hand) > 0) winners = [p]; else if (compareHands(p.hand, winners[0].hand) === 0) winners.push(p); }); const share = Math.floor(room.pot / Math.max(1, winners.length)); const rem = room.pot - share * winners.length; winners.forEach((w, i) => w.points += share + (i === 0 ? rem : 0)); room.reveal = activePlayers(room).map((p) => ({ playerId: p.id, cards: p.cards, hand: p.hand, winner: winners.some((w) => w.id === p.id), folded: p.folded })); room.handResult = { reason, winners: winners.map((w) => w.nickname), pot: room.pot }; addLog(room, `${winners.map((w) => w.nickname).join('、')} 赢得底池 ${room.pot} 分（${reason}）。`); checkEliminations(room); if (!checkGameOver(room, false)) writeRoom(room); }
function checkEliminations(room) { activePlayers(room).forEach((p) => { if (p.points <= 0) { p.points = 0; p.eliminated = true; p.folded = true; addLog(room, `${p.nickname} 临时积分归零，已淘汰，可选择旁观。`); } }); }
function checkGameOver(room, write = true) { const left = activePlayers(room); if (room && left.length <= 1 && room.phase !== 'waiting') { room.phase = 'gameFinished'; room.currentPlayerId = null; room.gameResult = { winnerId: left[0]?.id, winnerName: left[0]?.nickname || '无' }; addLog(room, `整场游戏结束，${room.gameResult.winnerName} 获胜。所有临时积分已清零。`); room.players.forEach((p) => { p.points = 0; p.spectator = false; p.spectateTargetId = null; resetHandPlayer(p); }); if (write) writeRoom(room); else state = room; return true; } return false; }
function maybeRunAI() { clearTimeout(aiTimer); const room = state; const current = room?.players?.find((p) => p.id === room.currentPlayerId); const hostControlsAI = room?.mode === 'local' || isHost(); if (!hostControlsAI || room.phase !== 'playing' || !current?.isAI) return; aiTimer = setTimeout(() => { const decision = decideAIAction(current, state); addLog(state, `${current.nickname}（${current.aiDifficulty} AI）：${decision.reason}`); sendAction(decision.action, current.id, decision); }, 600 + Math.random() * 500); }
function decideAIAction(p, room) { const opponents = liveHandPlayers(room).filter((x) => x.id !== p.id); const target = opponents[0]?.id; const need = Math.max(0, room.currentBet - p.bet); const h = p.hand.rank; const pressure = need > room.settings.ante * 2 || room.pot > room.settings.ante * opponents.length * 4; let compareChance = opponents.length === 1 ? .55 : .08; let foldChance = h <= 1 && pressure ? .42 : .14; let raiseChance = h >= 4 ? .5 : .22; const r = Math.random(); if (target && r < compareChance) return { action: 'compare', targetPlayerId: target, reason: '选择比牌推进本手' }; if (need > 0 && r < compareChance + foldChance) return { action: 'fold', reason: '成本偏高，选择弃牌' }; if (p.points > need + room.settings.ante && r < compareChance + foldChance + raiseChance) return { action: 'raise', amount: room.currentBet + room.settings.ante, reason: '选择加注施压' }; return { action: 'call', reason: '继续跟注' }; }
function startOnlineGame(withAI = false) { if (withAI) state.settings.allowAI = true; startGame(withAI); }
function toggleReady() { const room = structuredClone(state); const p = room.players.find((x) => x.id === playerId); if (p && !p.isHost && room.phase === 'waiting') { p.ready = !p.ready; addLog(room, `${p.nickname} ${p.ready ? '已准备' : '取消准备'}。`); writeRoom(room); } }
function chooseSpectateTarget() { const room = structuredClone(state); const p = room.players.find((x) => x.id === playerId); const t = room.players.find((x) => x.id === $('spectateTarget')?.value && !x.eliminated); if (p && t && p.eliminated && !p.spectateTargetId) { p.spectator = true; p.spectateTargetId = t.id; addLog(room, `${p.nickname} 开始旁观 ${t.nickname}。`); writeRoom(room); } }
function adjustRaiseAmount(delta) { const input = $('raiseAmount'); if (!input) return; const base = (state.currentBet || 0) + (state.settings.ante || 50); input.value = Math.max(base, (+input.value || base) + delta); }
function getActionHint(player = me()) { if (!player) return '当前浏览器未识别为本房间玩家，请重新加入房间'; if (player.eliminated) return '你已淘汰，可选择旁观'; if (player.spectator) return '旁观中，不能操作'; if (player.folded) return '你已弃牌，等待本手结束'; if (state?.phase === 'playing' && state.currentPlayerId === player.id) return player.looked ? '轮到你行动：你已看牌，可继续跟注、加注、弃牌或比牌' : '轮到你行动：你可以先看牌，也可以直接跟注'; if (state?.phase === 'playing') return '等待其他玩家行动'; return '当前阶段暂不能操作'; }
function render() { document.body.dataset.view = view; const content = state ? renderStatefulView() : renderViewWithoutRoom(); app.innerHTML = `${toast ? `<div class="panel toast">${toast}</div>` : ''}${content}${renderRuleIntroModal()}${renderLogModal()}`; toast = ''; }
function renderViewWithoutRoom() { if (view === 'soloSetup') return renderSoloSetup(); if (view === 'onlineEntry') return renderOnlineEntry(); return renderHome(); }
function renderStatefulView() { if (view === 'roomLobby' && state.phase === 'waiting' && state.mode === 'online') return renderRoomLobby(); return view === 'home' ? renderHome() : view === 'soloSetup' ? renderSoloSetup() : view === 'onlineEntry' ? renderOnlineEntry() : renderGameTable(); }
function settingsHtml(prefix = '', values = state?.settings || defaultLocalSettings(), includeAI = true) { return `<div class="form-grid settings-grid"><label class="form-field"><span>玩家人数</span><input id="${prefix}maxPlayers" type="number" min="2" max="8" value="${values.maxPlayers || 4}"></label><label class="form-field"><span>初始临时积分</span><input id="${prefix}initialPoints" type="number" value="${values.initialPoints || 1000}"></label><label class="form-field"><span>底注</span><input id="${prefix}ante" type="number" value="${values.ante || 50}"></label>${includeAI ? `<label class="form-field checkline"><span>电脑玩家</span><span class="inline-check"><input id="${prefix}allowAI" type="checkbox" ${values.allowAI !== false ? 'checked' : ''}>人数不足时自动加入 AI 玩家</span></label>` : ''}<label class="form-field"><span>AI 难度</span><select id="${prefix}aiDifficulty"><option value="easy">简单</option><option value="normal" selected>普通</option><option value="hard">困难</option><option value="aggressive">激进</option></select></label><label class="form-field checkline"><span>发牌动画</span><span class="inline-check"><input type="checkbox" checked>开启</span></label></div>`; }
function renderHome() { return `<section class="cover"><div class="cover-card"><span class="eyebrow">纯娱乐 · 扑克牌规则模拟</span><h2>炸金花娱乐模拟器</h2><p class="subtitle">纯娱乐扑克牌规则模拟，支持单机 AI 与 Firebase 联机房间。</p><p class="compliance-text">本游戏仅为规则娱乐模拟，不涉及真实金钱、充值、提现、兑换、奖励或任何形式的赌博行为。所有积分仅为本场临时娱乐分数，游戏结束后自动清零。</p><div class="cover-actions"><button class="primary-start" onclick="go('soloSetup')">单机模式</button><button class="outline-start" onclick="go('onlineEntry')">联机模式</button></div>${!db ? '<p class="notice-inline">联机模式需要配置 firebase-config.js；单机模式可直接使用。</p>' : ''}</div></section>`; }
function renderSoloSetup() { return `<section class="page-head"><button class="secondary" onclick="go('home')">返回首页</button><div><span class="eyebrow">Solo</span><h2>单机模式</h2><p>与 AI 玩家进行本地对局，练习牌型判断、下注、弃牌与比牌。</p></div></section><section class="grid"><div class="panel hero"><h3>快速开始</h3><p>默认 4 人：你 + 3 名普通 AI；初始临时积分 1000，底注 50。</p><label class="form-field"><span>你的名称</span><input id="soloNick" placeholder="可空，默认自动生成"></label><div class="form-actions"><button class="primary-start" onclick="quickStartLocalGame()">快速开始</button></div></div><div class="panel"><h3>自定义开始</h3>${settingsHtml('solo', defaultLocalSettings(), false)}<div class="form-actions"><button onclick="startCustomLocalGame()">开始单机游戏</button></div></div></section>`; }
function renderOnlineEntry() { return `<section class="page-head"><button class="secondary" onclick="go('home')">返回首页</button><div><span class="eyebrow">Online</span><h2>联机模式</h2><p>创建 Firebase 房间并复制房间码，或输入房间码加入好友对局。</p></div></section><section class="grid two"><div class="panel"><h3>创建房间</h3><div class="form-grid single"><label class="form-field"><span>你的名称</span><input id="hostNick" value="房主"></label></div><h4>房间参数</h4>${settingsHtml('online', defaultLocalSettings(), true)}<div class="form-actions"><button onclick="createOnlineRoom()">创建房间</button></div></div><div class="panel"><h3>加入房间</h3><div class="form-grid single"><label class="form-field"><span>你的名称</span><input id="joinNick" placeholder="可空，默认自动生成"></label><label class="form-field"><span>房间码</span><input id="roomCode" placeholder="输入 10 位房间码"></label></div><div class="form-actions"><button onclick="joinRoom()">加入房间</button></div></div></section>`; }
function renderRoomLobby() { const players = state.players || []; return `<section class="lobby"><div class="lobby-main panel"><div class="page-head compact"><button class="secondary" onclick="go('home')">返回首页</button><div><span class="eyebrow">Room Lobby</span><h2>房间大厅</h2><p>等待好友加入，房主可调整本场临时规则。</p></div></div><div class="room-code"><strong>${state.code}</strong><button class="secondary" onclick="copyRoomCode()">复制房间码</button><span>${players.length} / ${state.settings.maxPlayers} 人</span></div><div class="lobby-list">${players.map(renderLobbyPlayer).join('')}</div><div class="lobby-actions">${isHost() ? `<button onclick="startOnlineGame(false)">开始游戏</button><button class="secondary" onclick="startOnlineGame(true)">电脑玩家补足后开始</button><button class="danger" onclick="deleteRoom()">删除房间</button>` : `<button onclick="toggleReady()">${me()?.ready ? '取消准备' : '准备'}</button>`}</div></div>${isHost() ? `<aside class="panel"><h3>房主设置</h3>${settingsHtml('', state.settings, true)}</aside>` : ''}</section>`; }
function deleteRoom() { if (roomRef && confirm('确定删除该房间吗？')) roomRef.remove(); }
function renderLobbyPlayer(player) { return `<div class="lobby-player"><strong>${player.nickname}</strong><span>${player.isHost ? '房主' : '玩家'}</span><span>${player.isAI ? `AI ${player.aiDifficulty}` : '真人'}</span><span>${player.online || player.isAI ? '在线' : '已离线'}</span><span>${player.ready || player.isHost ? '已准备' : '未准备'}</span></div>`; }
function renderGameTable() { const self = me(); const opponents = (state.players || []).filter((p) => p.id !== self?.id); const top = opponents.filter((_, i) => i % 3 === 0), left = opponents.filter((_, i) => i % 3 === 1), right = opponents.filter((_, i) => i % 3 === 2); return `<section class="game-shell play-view"><div class="compact-topbar"><button class="secondary" onclick="go('home')">返回首页</button><button class="secondary" onclick="ruleIntroOpen=true;render()">规则介绍</button><button class="secondary" onclick="logOpen=true;render()">查看日志</button><span>模式：${state.mode === 'local' ? '单机' : '联机'}</span>${state.mode === 'online' ? `<span>房间：${state.code}</span><button class="secondary" onclick="copyRoomCode()">复制房间码</button>` : ''}${statusPills()}</div><div class="game-table-layout"><div class="opponents opponents-top">${top.map(renderCompactPlayerCard).join('')}</div><div class="table-middle"><div class="opponents opponents-left">${left.map(renderCompactPlayerCard).join('')}</div><div class="pot-area"><div class="deck-card back"></div><strong>底池 ${state.pot || 0}</strong><span>当前下注 ${state.currentBet || 0}</span><small>${state.phase === 'dealing' ? '正在发牌...' : state.phase === 'playing' ? '等待玩家行动' : state.phase === 'handFinished' ? '本手已结算' : state.phase === 'gameFinished' ? '整场已结束' : '准备中'}</small></div><div class="opponents opponents-right">${right.map(renderCompactPlayerCard).join('')}</div></div></div>${renderMyPlayerZone(self)}<div class="bottom-panels">${renderResult()}</div></section>`; }
function renderCompactPlayerCard(player) { const hr = state.reveal?.find((r) => r.playerId === player.id); return `<div class="compact-player-card ${state.currentPlayerId === player.id ? 'current' : ''} ${hr?.winner ? 'handWinner' : ''} ${player.eliminated ? 'eliminated' : ''}"><div class="compact-head"><strong>${player.nickname}</strong><span>${player.isAI ? 'AI' : '真人'}</span></div><div class="compact-meta"><span>${player.points} 分</span><span>投入 ${player.bet}</span></div><div class="compact-status">${player.spectator ? '旁观' : player.eliminated ? '已淘汰' : player.folded ? '已弃牌' : player.looked ? '已看牌' : '未看牌'}</div><div class="compact-cards">${renderCards(player)}</div></div>`; }
function renderMyPlayerZone(player) { if (!player) return `<section class="my-player-zone"><p>正在同步玩家状态...</p></section>`; const hr = state.reveal?.find((r) => r.playerId === player.id); return `<section class="my-player-zone ${state.currentPlayerId === player.id ? 'current' : ''} ${player.eliminated ? 'eliminated' : ''} ${hr?.winner ? 'handWinner' : ''}"><div class="my-player-info"><strong>${player.nickname} ${player.isHost ? '👑' : ''}</strong><span>${player.isAI ? 'AI ' + player.aiDifficulty : '我的座位'}</span><span>临时积分：${player.points}</span><span>本手投入：${player.bet}</span><span>状态：${player.spectator ? '旁观' : player.eliminated ? '已淘汰' : player.folded ? '已弃牌' : player.looked ? '已看牌' : '未看牌'}</span></div><div class="my-cards">${renderCards(player)}</div><div class="my-actions">${renderActions()}</div><p class="mini-compliance">仅娱乐模拟；积分为本场临时分数，结束清零。</p></section>`; }
function statusPills() { const current = state.players.find((p) => p.id === state.currentPlayerId)?.nickname || '无'; const left = state.players.filter((p) => !p.eliminated && !p.spectator).length; const hand = state.players.filter((p) => !p.eliminated && !p.spectator && !p.folded).length; return [`阶段：${state.phase}`, `底池：${state.pot || 0}`, `当前下注：${state.currentBet || 0}`, `行动：${current}`, `未淘汰：${left}`, `未弃牌：${hand}`].map((x) => `<span class="pill">${x}</span>`).join(''); }
function renderActions() { const p = me() || {}; const actionable = canAct(); const disabled = !actionable ? 'disabled' : ''; const targets = (state.players || []).filter((x) => x.id !== p.id && !x.eliminated && !x.spectator && !x.folded); const canSpectate = p.eliminated && !p.spectateTargetId; const step = state.settings?.ante || 50; const defaultRaise = (state.currentBet || 0) + step; return `<section class="action-panel ${actionable ? 'is-active' : 'is-waiting'}"><div class="action-panel-header"><div><h3>我的操作</h3><span>${getActionHint(p)}</span></div>${actionable ? '<b class="action-ready">轮到你行动</b>' : '<b class="action-lock">等待中</b>'}</div><div class="action-primary-row"><button class="action-main" ${disabled} onclick="sendAction('look')">看牌</button><button class="action-main" ${disabled} onclick="sendAction('call')">跟注</button></div><div class="raise-control"><label>加注金额</label><div class="raise-input-row"><button class="secondary" ${disabled} onclick="adjustRaiseAmount(-${step})">-${step}</button><input id="raiseAmount" type="number" min="${defaultRaise}" value="${defaultRaise}"><button class="secondary" ${disabled} onclick="adjustRaiseAmount(${step})">+${step}</button><button ${disabled} onclick="sendAction('raise')">加注</button></div><small>积分不足时，服务端会按当前剩余积分全下处理。</small></div><div class="compare-control"><label>选择比牌对象</label><div class="compare-row"><select id="compareTarget" ${disabled || !targets.length ? 'disabled' : ''}>${targets.map((t) => `<option value="${t.id}">${t.nickname}</option>`).join('')}</select><button ${disabled || !targets.length ? 'disabled' : ''} onclick="sendAction('compare')">比牌</button></div>${targets.length ? '' : '<small>暂无可比牌对象</small>'}</div><div class="danger-row"><span>弃牌后本手不再参与胜负</span><button class="danger" ${disabled} onclick="sendAction('fold')">弃牌</button></div>${canSpectate ? `<div class="spectate-control"><label>进入旁观</label><div class="compare-row"><select id="spectateTarget">${targets.map((t) => `<option value="${t.id}">${t.nickname}</option>`).join('')}</select><button onclick="chooseSpectateTarget()">选择旁观对象</button></div></div>` : p.spectateTargetId ? `<p>正在旁观：${state.players.find((x) => x.id === p.spectateTargetId)?.nickname || '旁观对象已淘汰'}</p>` : ''}</section>`; }
function renderCards(player) { const cards = player.cards; if (cards?.length && (state.phase === 'handFinished' || state.phase === 'gameFinished' || player.id === playerId && player.looked)) return cards.map((c, i) => card(c, i)).join(''); const cls = player.folded ? 'back foldBack' : 'back'; return [0, 1, 2].map((_, i) => `<div class="card ${cls}" style="animation-delay:${i * 80}ms"></div>`).join(''); }
function card(c, i) { return `<div class="card ${c.color}" style="animation-delay:${i * 80}ms"><div class="corner">${c.rank}<br>${c.suit}</div><div class="center">${c.suit}</div><div class="bottom">${c.rank}<br>${c.suit}</div></div>`; }
function renderResult() { if (state.phase === 'handFinished') return `<section class="panel result"><h2>本手结算</h2><p>赢家：${state.handResult?.winners?.join('、')} ｜ 底池：${state.handResult?.pot} ｜ 原因：${state.handResult?.reason}</p><ul>${(state.reveal || []).map((r) => `<li>${state.players.find((p) => p.id === r.playerId)?.nickname}：${r.hand?.description}${r.winner ? ' ✅' : ''}</li>`).join('')}</ul>${isHost() || state.mode === 'local' ? `<button onclick="startHand()">开始下一手</button>` : ''}</section>`; if (state.phase === 'gameFinished') return `<section class="panel"><h2>整场游戏结束</h2><p>最终胜者：${state.gameResult?.winnerName}。所有临时积分已清零。</p>${isHost() || state.mode === 'local' ? `<button onclick="startGame(true)">重新开始一场</button>` : ''}</section>`; return ''; }
function renderRuleIntroModal() { if (!ruleIntroOpen) return ''; const sections = [['游戏性质', '本游戏仅为扑克牌规则娱乐模拟，不涉及真实金钱、充值、提现、兑换、奖励或任何形式的赌博行为。页面中的积分只是本场游戏内的临时娱乐分数，用来模拟下注、跟注、加注和结算过程。整场游戏结束后，所有临时积分都会清零，不会保存为账户余额，也不能转让或兑换任何现实利益。'], ['游戏目标', '每位玩家在游戏开始时获得相同数量的临时积分。每一手牌中，玩家通过看牌、跟注、加注、弃牌和比牌参与对局。赢得一手牌的玩家获得本手底池。玩家临时积分归零后被淘汰。整场游戏会一直进行，直到场上只剩最后一名未淘汰玩家，该玩家成为本场胜者。'], ['一手牌流程', '每一手开始时，所有未淘汰玩家自动投入底注，并各自获得三张牌。玩家可以选择先不看牌继续行动，也可以点击“看牌”查看自己的三张牌。之后玩家按顺序行动，可以跟注、加注、弃牌或选择一名未弃牌玩家比牌。本手牌会在只剩一名未弃牌玩家时结束，该玩家赢得底池。'], ['可用操作', '看牌用于查看自己的三张牌，其他玩家仍然看不到你的牌；跟注是投入当前需要跟上的积分并继续留在本手；加注会提高当前下注额；弃牌表示放弃本手；比牌会选择另一名未弃牌玩家进行牌型比较，牌小的一方退出本手。'], ['牌型大小', '牌型从大到小依次为：豹子、顺金、金花、顺子、对子、散牌。'], ['点数比较', '点数大小顺序为：A > K > Q > J > 10 > 9 > 8 > 7 > 6 > 5 > 4 > 3 > 2。A-2-3 可以作为最小顺子，Q-K-A 可以作为最大顺子。花色不参与最终大小比较。'], ['淘汰与旁观', '积分归零的玩家会被淘汰，不能继续操作。被淘汰玩家可以选择一名仍在场上的玩家进行旁观，旁观对象一旦选择，本场游戏内不可更改。'], ['游戏结束', '本游戏不设置最大轮数。只有当场上只剩一名未淘汰玩家时，整场游戏才会结束。游戏结束后，系统显示最终胜者，并清空所有临时积分。']]; return `<div class="modal-mask" onclick="ruleIntroOpen=false;render()"><section class="rule-modal rich-rules" onclick="event.stopPropagation()"><div class="rule-modal-head"><h2>规则介绍</h2><button class="secondary" onclick="ruleIntroOpen=false;render()">关闭</button></div><div class="rule-sections">${sections.map(([title, text]) => `<article class="rule-section"><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section></div>`; }
function renderLogModal() { if (!logOpen) return ''; return `<div class="modal-mask log-mask" onclick="logOpen=false;render()"><section class="rule-modal log-modal" onclick="event.stopPropagation()"><div class="rule-modal-head"><h2>游戏日志</h2><button class="secondary" onclick="logOpen=false;render()">关闭</button></div><div class="logs">${(state?.logs || []).map((x) => `<div>${x}</div>`).join('')}</div></section></div>`; }
window.addEventListener('beforeunload', () => { if (state?.mode === 'online' && roomRef) { const p = state.players?.find((x) => x.id === playerId); if (p && !p.isAI) { p.online = false; roomRef.set(state); } } });
resumeSavedOnlineRoom();
render();
