const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const app = express();
const server = http.createServer(app);
const io = new Server(server);
app.use(express.static('public'));
const PORT = process.env.PORT || 3000;
const rooms = new Map();
const socketToRoom = new Map();
const cleanTimers = new Map();
const SUITS = ['♠','♥','♣','♦'];
const RANKS = ['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
const VAL = Object.fromEntries(RANKS.map((r,i)=>[r,i+2]));
const DEFAULT_SETTINGS={maxPlayers:4, initialPoints:1000, ante:50, allowAI:true, aiDifficulty:'normal', maxRounds:10};
function safeInt(v,d,min,max){v=parseInt(v,10); if(Number.isNaN(v)) return d; return Math.max(min,Math.min(max,v));}
function generateRoomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c='';do{c='';for(let i=0;i<10;i++)c+=chars[Math.floor(Math.random()*chars.length)];}while(rooms.has(c));return c;}
function addLog(room,msg){room.logs.unshift(`[${new Date().toLocaleTimeString()}] ${msg}`); room.logs=room.logs.slice(0,80);}
function makePlayer({id,socketId,nickname,isHost=false,isAI=false,aiDifficulty='normal',spectator=false}){return {id,socketId,nickname:nickname||`玩家${Math.floor(1000+Math.random()*9000)}`,isHost,isAI,aiDifficulty,online:!isAI,ready:false,points:0,bet:0,looked:false,folded:false,eliminated:false,spectator,spectateTargetId:null,cards:[],hand:null,lastAction:''};}
function createRoom(socket,nickname,mode='online',settings={},options={}){const code=generateRoomCode();const cleanSettings={...DEFAULT_SETTINGS,...settings};cleanSettings.maxPlayers=safeInt(cleanSettings.maxPlayers,DEFAULT_SETTINGS.maxPlayers,2,8);cleanSettings.initialPoints=safeInt(cleanSettings.initialPoints,DEFAULT_SETTINGS.initialPoints,100,99999);cleanSettings.ante=safeInt(cleanSettings.ante,DEFAULT_SETTINGS.ante,1,9999);cleanSettings.maxRounds=safeInt(cleanSettings.maxRounds,DEFAULT_SETTINGS.maxRounds,1,50);cleanSettings.allowAI=cleanSettings.allowAI!==false;cleanSettings.aiDifficulty=cleanSettings.aiDifficulty||'normal';const shouldAutoStart=(mode==='local'&&options.autoStart===true)||(mode==='online'&&options.onlineQuickStart===true);if(shouldAutoStart)cleanSettings.allowAI=true;const room={code,mode,phase:'waiting',settings:cleanSettings,players:[],pot:0,currentBet:0,round:0,handNo:0,currentPlayerId:null,logs:[],reveal:[],handResult:null,gameResult:null,aiTimer:null,deck:[]};const p=makePlayer({id:socket.id,socketId:socket.id,nickname,isHost:true});room.players.push(p);rooms.set(code,room);socket.join(code);socketToRoom.set(socket.id,code);addLog(room,`${p.nickname} 创建${mode==='local'?'本地人机':'联机'}房间。`);if(shouldAutoStart){addLog(room,mode==='local'?'本地快速开始：自动补齐 AI 并开始游戏。':'联机房间 + AI 快速开始：自动补齐 AI 并开始游戏。');startGame(code);}else{broadcastRoom(code);}return code;}
function joinRoom(code,socket,nickname){const room=rooms.get((code||'').toUpperCase()); if(!room) return socket.emit('errorMessage','房间不存在。'); if(room.players.length>=room.settings.maxPlayers) return socket.emit('errorMessage','房间已满。'); if(room.phase!=='waiting') return socket.emit('errorMessage','游戏已开始，暂不能加入。'); const p=makePlayer({id:socket.id,socketId:socket.id,nickname}); room.players.push(p); socket.join(room.code); socketToRoom.set(socket.id,room.code); addLog(room,`${p.nickname} 加入房间。`); broadcastRoom(room.code);}
function createDeck(){const d=[]; for(const s of SUITS) for(const r of RANKS) d.push({rank:r,suit:s,value:VAL[r],color:(s==='♥'||s==='♦')?'red':'black'}); return d;}
function shuffleDeck(deck){for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];} return deck;}
function normalizeStraight(vals){const s=[...vals].sort((a,b)=>b-a); const key=s.join(','); if(key==='14,3,2') return [3,2,1]; if(key==='14,13,12') return [14,13,12]; if(s[0]-1===s[1]&&s[1]-1===s[2]) return s; return null;}
function evaluateHand(cards){const vals=cards.map(c=>c.value).sort((a,b)=>b-a); const counts={}; vals.forEach(v=>counts[v]=(counts[v]||0)+1); const flush=cards.every(c=>c.suit===cards[0].suit); const straight=normalizeStraight(vals); const entries=Object.entries(counts).map(([v,c])=>({v:+v,c})).sort((a,b)=>b.c-a.c||b.v-a.v); let rank=1,name='散牌',values=vals;if(entries[0].c===3){rank=6;name='豹子';values=[entries[0].v];} else if(flush&&straight){rank=5;name='顺金';values=straight;} else if(flush){rank=4;name='金花';values=vals;} else if(straight){rank=3;name='顺子';values=straight;} else if(entries[0].c===2){rank=2;name='对子';values=[entries[0].v,...entries.filter(e=>e.c===1).map(e=>e.v).sort((a,b)=>b-a)];} return {rank,name,values,description:`${cards.map(c=>c.rank+c.suit).join('、')} ${name}`};}
function compareHands(a,b){if(a.rank!==b.rank)return a.rank>b.rank?1:-1; for(let i=0;i<Math.max(a.values.length,b.values.length);i++){const av=a.values[i]||0,bv=b.values[i]||0;if(av!==bv)return av>bv?1:-1;} return 0;}
function activePlayers(room){return room.players.filter(p=>!p.eliminated&&!p.spectator);}
function liveHandPlayers(room){return activePlayers(room).filter(p=>!p.folded);}
function resetTransient(p){Object.assign(p,{bet:0,looked:false,folded:false,cards:[],hand:null,lastAction:''});}
function startGame(code){const room=rooms.get(code); if(!room||room.phase==='playing'||room.phase==='dealing')return; if(room.settings.allowAI){let n=1; while(room.players.length<room.settings.maxPlayers){room.players.push(makePlayer({id:`AI_${code}_${n}_${Date.now()}`,nickname:`AI ${n}`,isAI:true,aiDifficulty:room.settings.aiDifficulty})); n++;}}
 if(room.players.length<2){addLog(room,'至少需要 2 名玩家才能开始。'); return broadcastRoom(code);} room.players.forEach(p=>{p.points=room.settings.initialPoints;p.eliminated=false;p.spectator=false;p.spectateTargetId=null;p.ready=false;resetTransient(p);}); room.gameResult=null; addLog(room,'房主开始游戏，所有临时积分已发放。'); startHand(code);}
function startHand(code){const room=rooms.get(code); if(!room)return; if(checkGameOver(code))return; room.phase='dealing'; room.handNo++; room.round=1; room.pot=0; room.currentBet=room.settings.ante; room.reveal=[]; room.handResult=null; room.deck=shuffleDeck(createDeck()); activePlayers(room).forEach(p=>{resetTransient(p); p.cards=[room.deck.pop(),room.deck.pop(),room.deck.pop()]; p.hand=evaluateHand(p.cards); const ante=Math.min(p.points,room.settings.ante); p.points-=ante; p.bet=ante; room.pot+=ante; if(ante<room.settings.ante) addLog(room,`${p.nickname} 底注不足，全下 ${ante} 分。`);}); const first=liveHandPlayers(room)[0]; room.currentPlayerId=first?.id||null; addLog(room,`第 ${room.handNo} 手开始，正在发牌。`); broadcastRoom(code); setTimeout(()=>{const r=rooms.get(code); if(!r||r.phase!=='dealing')return; r.phase='playing'; addLog(r,'发牌完成，进入操作阶段。'); broadcastRoom(code); runAITurn(code);},1300);}
function validateTurn(room,p){return room&&p&&room.phase==='playing'&&room.currentPlayerId===p.id&&!p.eliminated&&!p.spectator&&!p.folded;}
function pay(room,p,amt){amt=Math.max(0,Math.min(p.points,amt)); p.points-=amt; p.bet+=amt; room.pot+=amt; return amt;}
function nextTurn(room){const live=liveHandPlayers(room); if(live.length<=1)return finishHand(room.code,'只剩一名未弃牌玩家'); if(room.round>=room.settings.maxRounds)return finishHand(room.code,'达到最大轮数自动摊牌'); let idx=live.findIndex(p=>p.id===room.currentPlayerId); room.currentPlayerId=live[(idx+1)%live.length].id; if(idx===live.length-1) room.round++; broadcastRoom(room.code); runAITurn(room.code);}
function handleAction(code,pid,{action,amount,targetPlayerId}){const room=rooms.get(code),p=room?.players.find(x=>x.id===pid); if(!validateTurn(room,p))return; if(action==='look'){p.looked=true; p.lastAction='看牌'; addLog(room,`${p.nickname} 看牌。`); broadcastRoom(code); return;}
 if(action==='fold'){p.folded=true;p.lastAction='弃牌';addLog(room,`${p.nickname} 弃牌。`);return nextTurn(room);} if(action==='call'){const need=Math.max(0,room.currentBet-p.bet);const paid=pay(room,p,need);p.lastAction='跟注';addLog(room,`${p.nickname} ${paid<need?'积分不足全下':'跟注'} ${paid} 分。`);return nextTurn(room);} if(action==='raise'){const target=safeInt(amount,room.currentBet+room.settings.ante,room.currentBet+1,999999);const need=target-p.bet;const paid=pay(room,p,need);room.currentBet=Math.max(room.currentBet,p.bet);p.lastAction='加注';addLog(room,`${p.nickname} 加注到 ${room.currentBet} 分${paid<need?'（全下）':''}。`);return nextTurn(room);} if(action==='compare'){const t=liveHandPlayers(room).find(x=>x.id===targetPlayerId&&x.id!==p.id); if(!t)return; const cmp=compareHands(p.hand,t.hand); const loser=cmp>=0?t:p; loser.folded=true; loser.lastAction='比牌失败'; addLog(room,`${p.nickname} 与 ${t.nickname} 比牌，${loser.nickname} 输掉本手。`); return nextTurn(room);} }
function finishHand(code,reason){const room=typeof code==='string'?rooms.get(code):code; if(!room)return; room.phase='handFinished'; room.currentPlayerId=null; const contenders=liveHandPlayers(room); let winners=[]; if(contenders.length===1) winners=[contenders[0]]; else {for(const p of contenders){if(!winners.length||compareHands(p.hand,winners[0].hand)>0)winners=[p]; else if(compareHands(p.hand,winners[0].hand)===0)winners.push(p);}} const share=Math.floor(room.pot/Math.max(1,winners.length)),rem=room.pot-share*winners.length; winners.forEach((w,i)=>w.points+=share+(i===0?rem:0)); if(rem)addLog(room,`底池无法整除，余数 ${rem} 分给 ${winners[0].nickname}。`); room.reveal=activePlayers(room).map(p=>({playerId:p.id,cards:p.cards,hand:p.hand,folded:p.folded,winner:winners.some(w=>w.id===p.id)})); room.handResult={reason,winners:winners.map(w=>w.nickname),pot:room.pot}; addLog(room,`${winners.map(w=>w.nickname).join('、')} 赢得底池 ${room.pot} 分（${reason}）。`); checkEliminations(room.code); if(!checkGameOver(room.code)) broadcastRoom(room.code);}
function checkEliminations(code){const room=rooms.get(code); activePlayers(room).forEach(p=>{if(p.points<=0){p.points=0;p.eliminated=true;p.folded=true;addLog(room,`${p.nickname} 临时积分归零，已淘汰，可选择旁观。`);}});}
function checkGameOver(code){const room=rooms.get(code); const left=activePlayers(room); if(room&&left.length<=1&&room.phase!=='waiting'){finishGame(code,left[0]);return true;} return false;}
function finishGame(code,winner){const room=rooms.get(code); room.phase='gameFinished'; room.currentPlayerId=null; room.gameResult={winnerId:winner?.id,winnerName:winner?.nickname||'无'}; addLog(room,`整场游戏结束，${room.gameResult.winnerName} 获胜。所有临时积分已清零。`); room.players.forEach(p=>{p.points=0;p.spectator=false;p.spectateTargetId=null;resetTransient(p);}); broadcastRoom(code);}
function getPublicRoomState(room,viewer){return {...room,deck:undefined,players:room.players.map(p=>{let cards=null; const reveal=room.phase==='handFinished'; if(reveal) cards=p.cards; else if(p.id===viewer&&p.looked) cards=p.cards; return {id:p.id,nickname:p.nickname,isHost:p.isHost,isAI:p.isAI,aiDifficulty:p.aiDifficulty,online:p.online,ready:p.ready,points:p.points,bet:p.bet,looked:p.looked,folded:p.folded,eliminated:p.eliminated,spectator:p.spectator,spectateTargetId:p.spectateTargetId,current:p.id===room.currentPlayerId,lastAction:p.lastAction,cards,hand:reveal?p.hand:null};})};}
function broadcastRoom(code){const room=rooms.get(code); if(!room)return; for(const p of room.players.filter(x=>!x.isAI&&x.socketId)){io.to(p.socketId).emit('roomState',getPublicRoomState(room,p.id));}}
function decideAIAction(p,room){const h=p.hand.rank, need=Math.max(0,room.currentBet-p.bet), live=liveHandPlayers(room).filter(x=>x.id!==p.id); const target=live[0]?.id; const diff=p.aiDifficulty; const r=Math.random(); let raiseChance={easy:.12,normal:.25,hard:.33,aggressive:.48}[diff]||.25; let foldChance={easy:.12,normal:.25,hard:.18,aggressive:.08}[diff]||.2; if(h>=4){raiseChance+=.25;foldChance=0;} if(h<=1&&need>room.settings.ante*2) foldChance+=.25; if(live.length===1&&r<.25&&target)return {action:'compare',targetPlayerId:target,reason:'尝试比牌'}; if(r<foldChance&&need>0)return {action:'fold',reason:'牌力偏弱'}; if(r<foldChance+raiseChance&&p.points>need+room.settings.ante)return {action:'raise',amount:room.currentBet+room.settings.ante,reason:'选择加注'}; return {action:'call',reason:'继续跟注'};}
function runAITurn(code){const room=rooms.get(code); if(!room||room.phase!=='playing')return; const p=room.players.find(x=>x.id===room.currentPlayerId); if(!p?.isAI)return; clearTimeout(room.aiTimer); room.aiTimer=setTimeout(()=>{const r=rooms.get(code); const ai=r?.players.find(x=>x.id===r.currentPlayerId); if(!validateTurn(r,ai))return; const d=decideAIAction(ai,r); addLog(r,`${ai.nickname}（${ai.aiDifficulty} AI）：${d.reason}`); handleAction(code,ai.id,d);},500+Math.random()*700);}
io.on('connection',socket=>{socket.on('createRoom',d=>createRoom(socket,d?.nickname,d?.mode,d?.settings,{autoStart:!!d?.autoStart,onlineQuickStart:!!d?.onlineQuickStart})); socket.on('joinRoom',d=>joinRoom(d?.roomCode,socket,d?.nickname)); socket.on('updateSettings',s=>{const r=rooms.get(socketToRoom.get(socket.id));const p=r?.players.find(x=>x.id===socket.id); if(p?.isHost&&r.phase==='waiting'){r.settings={...r.settings,maxPlayers:safeInt(s.maxPlayers,6,2,8),initialPoints:safeInt(s.initialPoints,1000,100,99999),ante:safeInt(s.ante,50,1,9999),maxRounds:safeInt(s.maxRounds,10,1,50),allowAI:!!s.allowAI,aiDifficulty:s.aiDifficulty||'normal'};broadcastRoom(r.code);}}); socket.on('startGame',()=>{const r=rooms.get(socketToRoom.get(socket.id)); if(r?.players.find(p=>p.id===socket.id)?.isHost)startGame(r.code);}); socket.on('nextHand',()=>{const r=rooms.get(socketToRoom.get(socket.id)); if(r?.players.find(p=>p.id===socket.id)?.isHost&&r.phase==='handFinished')startHand(r.code);}); socket.on('restartGame',()=>{const r=rooms.get(socketToRoom.get(socket.id)); if(r?.players.find(p=>p.id===socket.id)?.isHost)startGame(r.code);}); socket.on('action',d=>handleAction(socketToRoom.get(socket.id),socket.id,d||{})); socket.on('spectate',tid=>{const r=rooms.get(socketToRoom.get(socket.id));const p=r?.players.find(x=>x.id===socket.id);const t=r?.players.find(x=>x.id===tid&&!x.eliminated&&!x.spectator); if(p&&p.eliminated&&!p.spectateTargetId&&t){p.spectator=true;p.spectateTargetId=t.id;addLog(r,`${p.nickname} 开始旁观 ${t.nickname}（本场不可更改）。`);broadcastRoom(r.code);}}); socket.on('disconnect',()=>{const code=socketToRoom.get(socket.id),r=rooms.get(code); if(!r)return; const p=r.players.find(x=>x.id===socket.id); if(p){p.online=false; addLog(r,`${p.nickname} 已断线。`); if(p.isHost){p.isHost=false; const nh=r.players.find(x=>!x.isAI&&x.online); if(nh){nh.isHost=true;addLog(r,`${nh.nickname} 成为新房主。`);}} if(!r.players.some(x=>!x.isAI&&x.online)) cleanTimers.set(code,setTimeout(()=>rooms.delete(code),60000)); broadcastRoom(code);} socketToRoom.delete(socket.id);});});
server.listen(PORT,()=>console.log(`Server running at http://localhost:${PORT}`));
